### ISSUE TITLE
POST request help

### ISSUE THREAD

**Issue by blindpet** [aondio/libvmod-bodyaccess#5]
I have found your quite old post [here](https://www.varnish-cache.org/lists/pipermail/varnish-misc/2012-August/022429.html) and was hoping you could elaborate.

I have a POST request that looks like this

```
action=ssbp_lazy&security=6cd3beb195&ssbppostid=992&ssbptitle=Setup+uTorrent+Server+Bloatware+Free&ssbpurl=http%3A%2F%2Fwww.htpcguides.com%2Fsetup-utorrent-server-bloatware-free%2F&ssbpshorturl=&ssbpsharetext
```
# 

and a response that looks like this

![image](https://cloud.githubusercontent.com/assets/8589960/10832777/a94545f6-7e8d-11e5-91d3-6a42b8d53d02.png)

Do I need to deal with the hash for both the request and the response? Here is what I have so far

```
import parsereq;
sub vcl_recv{
  parsereq.init();

If req.url ~ admin.ajax.php && req.method == "POST" {
    parsereq.post_body();
    return (hash); 

}
sub vcl_hash{
  hash_data(parsereq.post_header("hogehoge"));
}
```

What is hoge?

**Comment by aondio** [comment]
Hi,
this issue is not related to this VMOD.
The libvmod-parsereq is quite old and I really doubt it would work well for V4.0 or V4.1.
Please instead of opening github issues which are not issues, try to drop and email to our misc list (varnish-misc@varnish-cache.org) where you describe what you are trying to achieve or try to write on our irc channel.
Thanks

**Comment by blindpet** [comment]
Sorry about that, got confused. Have posted on parsereq git and will send an email to the misc list.
